name: salesforce-validate
on:
  pull_request:
#    types: [opened, synchronize, reopened, ready_for_review]
    branches: 
      - 'main'
    paths:
#      - 'force-app/**'
permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'
jobs:
  validate-job:
    name: Validate source code
#    runs-on: salesforce/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v3
        with:
           node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v5
        id: npm_cache_id
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run dummy sf command
        run: sf version
