name: salesforce-validate
on:
  pull_request:
#    types: [opened, synchronize, reopened, ready_for_review]
    branches: 
      - 'main'
    paths:
#      - 'force-app/**'
permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'
jobs:
  validate-job:
    name: Validate source code
#    runs-on: salesforce/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v3
        with:
           node-version: '14'
      - name: Install sf
        run: npm install -g @salesforce/cli@latest
      - name: Run dummy sf command
        run: sf version
